server:
  port: 8072
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
        cloud:
      routes:
        - id: licensing-service
          predicates:
          - Path=/licsvc/**
          uri: lb://LICENSING-SERVICE
          filters:
          - RewritePath=/licsvc/(?<segment>.*), /${segment}
        - id: organization-service
          predicates:
          - Path=/neworgsvc/**
          uri: lb://ORGANIZATION-SERVICE
          filters:
          - RewritePath=/neworgsvc/(?<segment>.*), /${segment}        
        
management:
  endpoints:
    web:
      exposure:
        include: "gateway,health,info,metrics,refresh"
  endpoint:
    gateway:
      enabled: true
    refresh:
      enabled: true
