spring:
  application:
    name: licensing-service
  profiles:
    active: dev
  config: 
    import: "optional:configserver:http://localhost:8071"

#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - refresh    
#  cloud:
#    config: 
#      uri: http://configserver:8071
        
#management:
#  endpoints:
#    web:
#      base-path: /
#    enabled-by-default: true
#  endpoint:
#    health:
#      enabled: true
#      show-details: always
#  health:
#    db:
#      enabled: false
#    diskspace:
#      enabled: true

      
